### ISSUE TITLE
postcss not found

### ISSUE THREAD

**Issue by omahane** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#11]
After running the following commands:
```
git clone https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development
ddev start
ddev build
```
I received the following error:
```
> storybook@1.0.0 generate-css
> postcss src/tailwind.css -o public/main.css

sh: 1: postcss: not found
Failed to run build : exit status 127
```

**Comment by omahane** [comment]
In another terminal, I just did the following
```
cd next
npm install -D postcss 
```
Then, when I ran `ddev build` in the first terminal, it built without error.

**Comment by vincentsig** [comment]
Same issue for me.

**Comment by omahane** [comment]
@vincentsig Were you ever able to get this to work?

**Comment by AndrewMac** [comment]
I am having the same issue. First problem was the same 'postcss not found' as the author. I followed his instructions and next time the build process worked without error.

But the site is still not loading without CSS styles, so it looks nothing like it should. I wonder if it's the "build:dev" command in the theme's package.json file, which is:

` "build:dev": "ls" `

But if it is, I'm not sure what to change it to. Or is it something else that's not working?

Thanks in advance for any help or advice you may be able to give with this.

**Comment by darkdim** [comment]
Hello
I made a commit, but it hasn't been accepted yet.
There is a need to add the command yarn install to the build
`cd storybook; yarn install; npm run generate-css`

**Comment by lussoluca** [comment]
Sorry for this late reply. 
A fix is on the way :-)

**Comment by dalemoore** [comment]
Was this fixed? I literally started just now and didn't receive this error (on an Intel Mac).

**Comment by dalemoore** [comment]
I meant to edit my post... but I am just getting started, and everything works fine except the demo site has no styles as mentioned above. On an Intel Mac.

**Comment by artiste1212** [comment]
Hi, any luck on the fix for this? Or is dalemoore correct that the website isn't supposed to look like that yet?

**Comment by vincentsig** [comment]
Still confusing for me too. But I think the style should be generated.

**Comment by dalemoore** [comment]
I'm now on page 174 and can confirm the site isn't supposed to look like the final yet. You work to make it look like that by moving forward in the book. Should have been obvious I guess, but the phrasing earlier in the book was confusing me.

**Comment by lussoluca** [comment]
Hi, there is an issue with the picture 1.6 on page 14.

When you start from the `main` branch the site is (correctly) unstyled.
The picture is the result of building the demo website starting from the `final` branch.
Sorry for the confusion, I'm going to update the [errata](https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md) file.

**Comment by omahane** [comment]
Thank you for that clarification. It makes sense that it's unstyled, which is definitely why the picture threw me off.
