### ISSUE TITLE
Question: Any suggestion on how to handle sass + postcss

### ISSUE THREAD

**Issue by smustgrave** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#15]
First off the book is very good! Been really enjoying the examples.

Tailwind is a good example but another library that has been a requirement is [USWDS](https://github.com/uswds/uswds) which is built with [USWDS Compile](https://github.com/uswds/uswds-compile), which is a sass solution.  So wonder if you have any suggestion on when/how to use both sass + postcss?

Is it bad to actually use both?

**Comment by lussoluca** [comment]
Hi, Tailwind has been chosen to simplify the CSS part of the book.
You can, of course, use whatever CSS preprocessor you want. Usually, you want to use Sass or Postcss, not both; you have to adapt the Webpack configuration to your needs.
