### ISSUE TITLE
Chapter-by-chapter code?

### ISSUE THREAD

**Issue by dalemoore** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#17]
Hi,

Is there a place somewhere where we can get the code for the files used chapter-by-chapter, not just the final (there's WAY too much added/removed in the final to be helpful)? I'm having a heck of a time getting even the basics to work. I'm typing the code exactly as it's written in the book, but running into issues. If I have a file with the code for each chapter that I can compare it to it can help me determine if I'm overlooking typos or something simple.

For instance, on page 38 it says to run (I assume within the themes/custom/alps_trips folder, since that's where we last left off):

`node_modules/.bin/webpack --config webpack.config.js --mode development`

I've done that, and then it says

`bash: node_modules/.bin/webpack: No such file or directory`

Okay, makes sense. The node_modules folder is actually in the web directory. So, cd back up to `web` and run the line above again.

```
[webpack-cli] Failed to load '/var/www/html/web/webpack.config.js' config
[webpack-cli] Error: Cannot find module '/var/www/html/web/webpack.config.js'
Require stack:
- /var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js
- /var/www/html/web/node_modules/webpack-cli/lib/bootstrap.js
- /var/www/html/web/node_modules/webpack-cli/bin/cli.js
- /var/www/html/web/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at WebpackCLI.tryRequireThenImport (/var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js:223:30)
    at loadConfigByPath (/var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js:1406:38)
    at /var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js:1460:88
    at Array.map (<anonymous>)
    at WebpackCLI.loadConfig (/var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js:1460:68)
    at WebpackCLI.createCompiler (/var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js:1781:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/html/web/node_modules/webpack-cli/lib/webpack-cli.js',
    '/var/www/html/web/node_modules/webpack-cli/lib/bootstrap.js',
    '/var/www/html/web/node_modules/webpack-cli/bin/cli.js',
    '/var/www/html/web/node_modules/webpack/bin/webpack.js'
  ]
}
```

Okay, well, webpack.config.js isn't in the `web` directory either. So maybe I have to add the path to that? No, that doesn't work, either.

I have to be missing something simple. :\

**Comment by dalemoore** [comment]
I figured out my issue. While page 36 has you add the line

`import "../css/tailwind.css";`

The instructions never actually tell you explicitly (or at least, not explicitly enough for a "tired-probably-should-have-started-this-in-the-morning-when-more-refreshed" me) that you must create that file in that directory, right then. I was thinking that later steps would add a file with that filename there. 😅 Once I added a blank tailwind.css file in /css/, and ran

`node_modules/.bin/webpack --config webpack.config.js --mode development`

in the `alps_trips` folder, it worked fine. Leaving this here for future if anyone screws up like me.

**Comment by dalemoore** [comment]
Ran into another problem. On page 39, there's an error:

`main:
  version: VERSION
  js:
    build/main.js: {}
  css:
    theme:
      build/main.css: {}
   `
should be

`main:
  version: VERSION
  js:
    build/main.js: {}
  css:
    theme:
      build/styles.css: {}
   `
There's no main.css.

**Comment by dalemoore** [comment]
I think I may have run into a problem.

On page 39, I think

`build/main.css: {}`

should be

`build/styles.css: {}`

should it not? The main.css file is in the /css/ folder, not the /build/ folder. If I change that to styles.css, the browsersync stuff works. If I don't, it doesn't. On page 38, it looks like it's being added to /build/styles.css.

**Comment by lussoluca** [comment]
Hi, there is an errata file on the repo with all the issues in text that we've found so far: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md.

Check that file, and feel free to contribute if you find something wrong.

Thanks
