### ISSUE TITLE
Errata on p 18

### ISSUE THREAD

**Issue by omahane** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#26]
While reading the note in "Disabling production optimization," I noticed an issue.

The following text looks like it's been added in error:
> This text is not part of the note. It must be moved outside, just before the next sertence
At the end...)
<img width="1122" alt="Screenshot 2023-10-31 at 11 45 33 AM" src="https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/assets/766573/475d550a-1e10-4417-b997-f383408e955b">

**Comment by lussoluca** [comment]
Good catch, thanks!
I add it to the errata file

**Comment by lussoluca** [comment]
Added
