### ISSUE TITLE
Erratum on page 21

### ISSUE THREAD

**Issue by omahane** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#27]
In the paragraph after the code block from `settings.local.php`, there's a sentence:
> By removing the comments, we force the cache bins that deal with HTML generation to use the cache. backend. nu11 service that we added in the `default.services.ymI` file.

I believe the it should read `development.services.yml`.
![Modernizing Drupal 10 Theme Development eBook pdf - page 44](https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/assets/766573/9a147893-8446-41ed-a086-bb8edc2dc0eb)

**Comment by lussoluca** [comment]
Thanks, I've added it to the errata file: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-1
