### ISSUE TITLE
MIME type error with main.css file - Chrome refuses to apply style

### ISSUE THREAD

**Issue by artiste1212** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#31]
I'm trying to follow along in chapter 5, styling the header and footer. I'm still not seeing any styling, just plain HTML. When I opened the element inspector in Chrome, I noticed two errors. Both of them are "Refused to apply style from 'https://packt.ddev.site/themes/custom/alps_trips/build/main.css?s3w5jd' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled." I believe that this may be preventing me from seeing the Tailwind CSS classes. How can I solve this issue?

**Comment by lussoluca** [comment]
The `build/main.css` file doesn't exist; it's a typo. It should be `build/styles.css`.
This has been added here: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-2
