### ISSUE TITLE
missing template file name in chapter 6

### ISSUE THREAD

**Issue by artiste1212** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#32]
Hi, at location 4139 in the ebook (sorry I don't have the physical book to get a page number), in chapter 6 (Styling the Content), in the section about rendering latitude and longitude data as a map with pointer, the book says "Finally, we need a template to render the alps_base_lat_lng theme hook." The book doesn't provide a name for this template file, as it usually does. What should we call this template file?

**Comment by lussoluca** [comment]
Hi, @artiste1212.
I'm slowly reviewing all your issues.

I've added a point for this one in the errata file: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-6

**Comment by artiste1212** [comment]
Thank you so much. Sorry that I'm really a beginner, so I get tripped up by things which most of your readers would probably be able to understand without much effort.
