### ISSUE TITLE
No CSS Showing

### ISSUE THREAD

**Issue by mkefiles** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#34]
In reference to PG14, my version of the site does not appear to have any CSS so it does not look like the image in the book. If it helps, I am running Windows 11 Home using an installation of DDEV on Ubuntu through WSL.

**Comment by omahane** [comment]
@mkefiles This issue has been addressed here https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/issues/11
