### ISSUE TITLE
Error: File Not Found - css/tailwind.css.js  : chapter 2

### ISSUE THREAD

**Issue by hamad2** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#37]
I tried to follow the command for installing webpack using the command node_modules/.bin/webpack --config webpack.config.js --mode development. I got two errors -- I got the following output:
`ERROR in ./js/main.js 1:0-29
Module not found: Error: Can't resolve '../css/tailwind.css' in '/var/www/html/web/themes/custom/alps_trips/js'
resolve '../css/tailwind.css' in '/var/www/html/web/themes/custom/alps_trips/js'
  using description file: /var/www/html/web/themes/custom/alps_trips/package.json (relative path: ./js)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /var/www/html/web/themes/custom/alps_trips/package.json (relative path: ./css/tailwind.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /var/www/html/web/themes/custom/alps_trips/css/tailwind.css doesn't exist`

I think we should rename  css/main.css to css/tailwind.css    in my case that worked for me. 
Please correct.

**Comment by lussoluca** [comment]
Yes, there is a typo in the book. Please take a look at the errata file here: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md

**Comment by chrisvetek** [comment]
thanks for pointing out what the ERRATA.md file was for :)
