### ISSUE TITLE
Theme appears to be missing

### ISSUE THREAD

**Issue by pikadroo** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#38]
I've installed everything and there is no styling in the Drupal 10 site. it's just plain text links and images. The actual CSS code or styling in the theme appears to be missing?

**Comment by lussoluca** [comment]
Yes, sorry for that, but we published the wrong image. Here the correct version: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-1

**Comment by pikadroo** [comment]
I’ve posted another issue I am having I am really in need of a response on how to resolve my error and this is taking a lot of time. I am under a deadline to get thru this and the continuing roadblocks are preventing me from moving forward. I can not get past page 35 in the book.
