### ISSUE TITLE
Clarification needed for composer install –prefer-dist

### ISSUE THREAD

**Issue by apprentia** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#42]
Hello,

I am running through the set-up process in the book and when I use : 

`composer install –prefer-dist`

I am getting the following message : 

> Invalid argument –prefer-dist. Use "composer require –prefer-dist" instead to add packages to your composer.json.

The site is up and running but the theme has not been built as a result.

If I use `composer require –prefer-dist` I am prompted to choose from a list of profiles but nothing to do with the book, I think.

**Comment by imaaxa** [comment]
Try composer require --prefer-dist.
The editing software used for the book replaced the double hyphen(--) with a different character, (–).

**Comment by lussoluca** [comment]
Exactly, this has been reported here: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-1
