### ISSUE TITLE
Please help provide detailed steps on Storybook Integrations 

### ISSUE THREAD

**Issue by virdurm** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#46]
Hi, in the Chapter "Mapping the Design to Drupal Components", there's a paragraph saying, 
/** excerpt from the book **/

We’ve chosen **Storybook** because it can be installed locally and supports Twig files...If you followed the steps described in Chapter 1, Setting Up a Local Environment, you already have an instance of Storybook up and running at [https://packt.ddev.site:6006].

/** end of the excerpt from the book **/

However, could you help share steps on integrating storybook into a newly installed drupal website ? I searched online, including storybook official documentations, but I still got errors during my hands-on integration process. I hence come to ask for help.

**Comment by lussoluca** [comment]
Probably the best way to integrate Storybook with Drupal nowadays is by using the Storybook Drupal module: https://www.drupal.org/project/storybook

**Comment by virdurm** [comment]
Honoured to obtain reply directly from you the author. Thanks Lusso Luca.

With project oriented principles, your book reads very interesting. Do you
have plans to deliver live site building video courses on popular platforms
like Udemy? I wish to be the first buyer.

**Comment by lussoluca** [comment]
> Do you
> have plans to deliver live site building video courses on popular platforms
> like Udemy?

Not at the moment, but maybe in the future 😉 

I'm closing this issue; feel free to open a new one if you have any other questions.
