### ISSUE TITLE
typo for adding main.js under webpack instructions

### ISSUE THREAD

**Issue by chrisvetek** [PacktPublishing/Modernizing-Drupal-10-Theme-Development#58]
There is wording stating the following:
import "../css/tailwind.css";
This file does not exist, it should say
import "../css/main.css"
This caused a few hours of debugging things that did not need to even be debugged.
All good, helped me learn.
Putting out for others.

**Comment by chrisvetek** [comment]
fix is in the description of the issue

**Comment by aXb0t** [comment]
@chrisvetek there are a number of notes in the ERRATA that will save some time for additional chapters: https://github.com/PacktPublishing/Modernizing-Drupal-10-Theme-Development/blob/main/ERRATA.md#chapter-2
